# Generated by Django 5.2.1 on 2025-08-19 17:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
