# Generated by Django 5.2.1 on 2025-08-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_project_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProjectCategory',
            new_name='ProjectTag',
        ),
        migrations.AlterModelOptions(
            name='projecttag',
            options={'ordering': ['name'], 'verbose_name': 'Project Tag', 'verbose_name_plural': 'Project Tags'},
        ),
        migrations.RemoveField(
            model_name='project',
            name='category',
        ),
        migrations.AddField(
            model_name='project',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='project_tags', to='home.projecttag'),
        ),
    ]
