# Generated by Django 5.2.1 on 2025-08-20 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_projectcategory_projecttag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.TextField(max_length=300),
        ),
    ]
