# Generated by Django 5.2.1 on 2025-08-20 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.TextField(max_length=160),
        ),
    ]
