# Generated by Django 5.2.1 on 2025-08-20 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=170),
        ),
        migrations.AlterField(
            model_name='project',
            name='link',
            field=models.TextField(),
        ),
    ]
