# Generated by Django 5.2.1 on 2025-09-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('month', models.CharField(max_length=8)),
                ('timeline_title', models.CharField(max_length=50)),
                ('timeline_description', models.CharField(max_length=160)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Timeline',
                'verbose_name_plural': 'Timelines',
                'ordering': ['created_on'],
            },
        ),
    ]
