# Generated by Django 5.2.1 on 2025-09-04 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_timeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='timeline_title',
            field=models.CharField(max_length=80),
        ),
    ]
