# Generated by Django 5.2.1 on 2025-09-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_timeline_timeline_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeline',
            name='month',
            field=models.CharField(max_length=10),
        ),
    ]
