# Generated by Django 5.2.1 on 2025-09-04 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_timeline_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
