# Generated by Django 5.2.1 on 2025-09-04 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_timeline_updated_on'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timeline',
            options={'ordering': ['updated_on'], 'verbose_name': 'Timeline', 'verbose_name_plural': 'Timelines'},
        ),
    ]
